# Generated by Django 4.2 on 2023-05-04 14:23

import accounts.models
import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accomplishments', '0001_initial'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'verbose_name': "Client's Profile", 'verbose_name_plural': "Clients' Profiles"},
        ),
        migrations.AlterModelOptions(
            name='expertprofile',
            options={'verbose_name': "Expert's Profile", 'verbose_name_plural': "Experts' Profiles"},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='profile',
        ),
        migrations.AddField(
            model_name='abstractprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city'),
        ),
        migrations.AddField(
            model_name='abstractprofile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country'),
        ),
        migrations.AddField(
            model_name='abstractprofile',
            name='date_birth',
            field=models.DateField(default=datetime.date(2005, 5, 8)),
        ),
        migrations.AddField(
            model_name='abstractprofile',
            name='gender',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'non-binary'), (3, 'transgender'), (4, 'intersex'), (5, 'prefer not to say')], default=5), default=accounts.models.AbstractProfile.get_default_gender, max_length=2, size=2),
        ),
        migrations.AddField(
            model_name='abstractprofile',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.region'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='education',
            field=models.ManyToManyField(blank=True, to='accomplishments.education'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='education_extra',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
