# Generated by Django 4.2 on 2023-05-10 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_clientprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractprofile',
            name='date_birth',
            field=models.DateField(default=datetime.date(2005, 5, 14)),
        ),
    ]
