# Generated by Django 4.2 on 2023-05-02 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_abstractprofile_city_abstractprofile_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='education_extra',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_degree', models.SmallIntegerField(choices=[(0, 'bachelor'), (1, 'master'), (2, 'doctor')], default=0)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.university')),
            ],
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='education',
            field=models.ManyToManyField(blank=True, to='accounts.education'),
        ),
    ]
