# Generated by Django 4.2 on 2023-05-03 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_university_expertprofile_education_extra_education_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'verbose_name': "Client's Profile", 'verbose_name_plural': "Clients' Profiles"},
        ),
        migrations.AlterModelOptions(
            name='expertprofile',
            options={'verbose_name': "Expert's Profile", 'verbose_name_plural': "Experts' Profiles"},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'University', 'verbose_name_plural': 'Universities'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='profile',
        ),
    ]
