# Generated by Django 4.2 on 2023-05-03 12:20

import accounts.models
import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_clientprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractprofile',
            name='date_birth',
            field=models.DateField(default=datetime.date(2005, 5, 7)),
        ),
        migrations.AddField(
            model_name='abstractprofile',
            name='gender',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'non-binary'), (3, 'transgender'), (4, 'intersex'), (5, 'prefer not to say')], default=5), default=accounts.models.AbstractProfile.get_default_gender, max_length=2, size=2),
        ),
    ]
