# Generated by Django 4.2 on 2023-05-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_speciality_education_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='university_degree',
            field=models.SmallIntegerField(choices=[(0, 'courses'), (1, 'undergraduate'), (2, 'specialist'), (3, 'master'), (4, 'postgraduate'), (5, 'doctor')], default=0),
        ),
    ]
