# Generated by Django 4.2 on 2023-05-04 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('code_ua', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'Speciality',
                'verbose_name_plural': 'Specialities',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_degree', models.SmallIntegerField(choices=[(0, 'courses'), (1, 'undergraduate'), (2, 'specialist'), (3, 'master'), (4, 'postgraduate'), (5, 'doctor')], default=0)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('speciality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accomplishments.speciality')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accomplishments.university')),
            ],
        ),
    ]
